# -*- coding: utf-8 -*-
# Copyright (c) 2020, GreyCube Technologies and contributors
# For license information, please see license.txt

from __future__ import unicode_literals
import frappe
from frappe.desk.page.setup_wizard.setup_wizard import make_records

def install_fixtures():
    records = [
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Sales Order",
  "enabled": 1,
  "event": "Submit",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer}},<br><br>\n\nThank you for your reservation at Sunfit.<br><br> \n\nBooking details<br><br>\n\nGuest Name: {{doc.guest_cf}}<br>\nArrival Date: {{doc.check_in_cf}}<br>\nRoom Type: {{doc.room_type_cf}}<br>\nRate/Night:{{doc.room_rate_cf}}<br><br>\n\nPayment Details<br><br>\n\nSunfit International Ltd<br>\nFidelity Bank<br>\nAcct No.: 4010480839</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:50.369249",
  "module": "",
  "name": "Reservation Confirmation",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Reservation Confirmation",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "contact_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Client Appointment",
  "enabled": 1,
  "event": "New",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer_name}},<br><br>\n\nThank you for your spa reservation at Sunfit.<br><br> \n\nBooking details<br><br>\n\nName: {{doc.customer_name}}<br>\nTreatment Type: {{doc.service}}<br>\nBooking Date and Time: {{doc.scheduled_from_date}}<br><br>\n\nPayment Details<br><br>\n\nSunfit International Ltd<br>\nFidelity Bank<br>\nAcct No.: 4010480839 </i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:50.194059",
  "module": "",
  "name": "Spa Booking Confirmation",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Spa Booking Confirmation",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "customer_phone_number",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "doc.status==\"Cancelled\" and doc.facility in ['Spa-Male','Spa-Female']",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Client Appointment",
  "enabled": 1,
  "event": "Save",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer_name}},<br><br>\n\nYour spa booking has been cancelled.<br><br> \n\nIf you would like to make a new booking or have any inquiries, please contact our 24 hours reception desk on 08096320300, 08096320302; or book online at www.sunfitltd.com/book_services</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:49.878867",
  "module": "",
  "name": "Your booking has been Cancelled",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Your booking has been Cancelled",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "customer_phone_number",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Sales Order",
  "enabled": 1,
  "event": "Cancel",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer}},<br><br>\n\nYour reservation at Sunfit has been cancelled.<br><br> \n\nIf you would like to make a new booking or have any inquiries, please contact our 24 hours reception desk on 08096320300, 08096320302; or book online at www.sunfitltd.com/room_booking</p></i>",
  "method": "",
  "modified": "2021-01-20 09:36:50.322663",
  "module": "",
  "name": "Your Reservation has been Cancelled",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Your Reservation has been Cancelled",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "contact_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Room Folio HMS",
  "enabled": 1,
  "event": "New",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.room_guest_detail[0].first_name}}<br><br>\n\nWe are delighted to have you at SUNFIT.<br><br>\n\nOur service hours are:<br><br>\n- Gym: 5am to 11pm<br>\n- Spa: 8am to 10pm<br>\n- Pool: 8am to 8pm<br>\n- Salon & Events: On request<br><br>\n\nPlease call the reception on 111 for any assistance needed. For feedback, please call the Manager on 08096320250.<br><br>\n\nWe wish you a very pleasant stay!!!</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:48.798072",
  "module": "",
  "name": "Welcome Letter",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Welcome Letter",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "customer_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Payment Entry",
  "enabled": 1,
  "event": "Custom",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.party_name}},<br><br>\n\nYour Club Membership has been activated.<br><br> \n\nStart Date: {{current_invoice_start}}<br> \nEnd Date: {{current_invoice_end}}<br><br>\n\n\nYour login ID is: {{member_web_login_id}}.<br><br> \nClick on the link below to access your membership page.<br><br>\n\n<a href =\"{{ frappe.get_url()}}/membership?membership={{name}}\">My Club Membership - Link</a><br><br>\n\nFor feedback, please call the Manager, Tonia on 08096320250.<br><br>\n\nWelcome to SUNFIT!!!</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:48.708601",
  "module": "",
  "name": "membership_active",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "membership_active",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "contact_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "doc.payment_type == \"Receive\"",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Payment Entry",
  "enabled": 1,
  "event": "Submit",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Thank you for your patronage.<br><br>\n\nYour payment of {{doc.paid_amount}} has been received.<br><br>\n\nFor feedback and enquiries, please call our 24 hours reception desk on 08096320250. Or contact our marketing unit, Esther on 0809589089</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:50.075254",
  "module": "",
  "name": "Payment Receipt",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Payment Receipt",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "contact_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Payment Entry",
  "enabled": 1,
  "event": "Cancel",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Thank you for your patronage.\n\nYour payment of {{doc.paid_amount}} has been cancelled. \n\nFor feedback and enquiries, please call our 24 hours reception desk on 08096320250. Or contact our marketing unit, Esther on 0809589089</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:50.144595",
  "module": "",
  "name": "Payment Cancellation",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Payment Cancellation",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "contact_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "birth_date_cf",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Contact",
  "enabled": 1,
  "event": "Custom",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.first_name}},<br><br>\n\nWe all at Sunfit are extremely excited to celebrate this special day with you.<br><br>\n\nMay your days be filled with prosperity, great health and above all joy in its truest and purest form.<br><br>\t\n\nHappy Birthday!!!</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:48.864047",
  "module": "",
  "name": "birthday_reminder",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "birthday_reminder",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "mobile_no",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Membership Suspension CT",
  "enabled": 1,
  "event": "Submit",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer}},<br><br>\n\nYour Club Membership has been suspended from {{doc.from_date}} to {{doc.to_date}}. Your membership renewal date will now be {{frappe.format_date(new_membership_end_date(doc.name))}}\n.<br><br>\n\nFor modifications, kindly contact Esther on 0809589089<br><br>\n\nStay Active, Live Healthy & Love Life!!!</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:50.279180",
  "module": "",
  "name": "Your Membership has been Suspended",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Your Membership has been Suspended",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "customer_mobile_no",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "current_invoice_end",
  "days_in_advance": 7,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Membership CT",
  "enabled": 1,
  "event": "Days Before",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer}},<br><br>\n\nYour Club Membership will expire on {{doc.current_invoice_end}}.<br><br> \n\nFor assistance, kindly contact Esther on 0809589089<br><br>\n\nStay Active, Live Healthy & Love Life!!!</p></i>",
  "method": "",
  "modified": "2021-01-20 09:36:48.955285",
  "module": "",
  "name": "Your Membership is about to Expire.",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Your Membership is about to Expire.",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "customer_mobile_no",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": """",
  "channel": "SMS",
  "condition": "",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Payment Entry",
  "enabled": 1,
  "event": "Custom",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.party_name}},<br><br>\n\nYour Club Membership has been renewed from {{current_invoice_start}} to {{current_invoice_end}}.<br><br> \n\nPlease log in below to view your membership profile.<br><br>\n<a href =\"{{ frappe.get_url()}}/membership?membership={{name}}\">Client Portal \u2013 Link</a><br><br>\n\nStay Active, Live Healthy & Love Life!!!</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:48.910014",
  "module": "",
  "name": "membership_renewal",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "membership_renewal",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "contact_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": "current_invoice_start"
 },
 {
  "channel": "SMS",
  "condition": "doc.status==\"Active Paid\"",
  "date_changed": "last_accessed_on",
  "days_in_advance": 14,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Membership CT",
  "enabled": 1,
  "event": "Condition Days After",
  "interval": "Every 15 days",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer}},<br><br>\n\nWe haven\u2019t seen you in a while; we\u2019re just checking in.<br><br> \n\nIf you need any assistance, or have any feedback or enquiries, please contact our marketing manager, Esther on 0809589089 or the Manager, Tonia on 0809 632 0250.<br><br>\n\nStay Active, Live Healthy and Love Life!!!</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:50.410161",
  "module": "",
  "name": "Just Checking In",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Just Checking In",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "contact_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "channel": "SMS",
  "condition": "doc.customer_group == \"Club Member\" and doc.disabled == 0",
  "date_changed": "last_fitness_checked_on",
  "days_in_advance": 24,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Customer",
  "enabled": 1,
  "event": "Condition Days After",
  "interval": "25th of every month",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer_name}},<br><br>\n\t\t\nIn our busy lives, we may forget to take care of \u201cour health\u201d.<br><br> \n\nThis is to remind you to check your Blood Pressure today.<br><br> \n\nStay Active, Live Healthy and Love Life!!!</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:50.458074",
  "module": "",
  "name": "Reminder: Check your Blood Pressure",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Reminder: Check your Blood Pressure",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "customer_mobile_no",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "channel": "SMS",
  "condition": "doc.customer_group == \"Club Member\" and doc.disabled == 0",
  "date_changed": "last_fitness_checked_on",
  "days_in_advance": 89,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Customer",
  "enabled": 1,
  "event": "Condition Days After",
  "interval": "Every 3 months",
  "is_standard": 0,
  "message": "<p><i>Dear{{doc.customer_name}},<br><br>\n\t\t\nRemember to update your fitness metrics on your next visit to the gym.<br><br>\n\nLog in below to view your membership profile.<br><br>\n<a href =\"{{ frappe.get_url() }}+'/membership?membership='+{{ doc.name }}\">Client Portal - Link</a><br><br>\n\nStay Active, Live Healthy and Love Life!!!</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:50.529947",
  "module": "",
  "name": "Update Your Fitness Metrics",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Update Your Fitness Metrics",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "customer_mobile_no",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": "",
  "channel": "SMS",
  "condition": "doc.amended_from is not None",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Sales Order",
  "enabled": 1,
  "event": "Submit",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer}},<br><br>\n\nYour reservation has been modified as follows:<br><br>\n\n<b>Booking details</b><br><br>\n\nGuest Name: {{doc.guest_cf}}<br>\nArrival Date: {{doc.check_in_cf}}<br>\nRoom Type: {{doc.room_type_cf}}<br>\nRate/Night: {{doc.room_rate_cf}}</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:49.930795",
  "module": "",
  "name": "Your Reservation has been Modified",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Your Reservation has been Modified",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "contact_mobile",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": ""
 },
 {
  "_liked_by": "",
  "channel": "SMS",
  "condition": "doc.status==\"Rescheduled\" and doc.facility in ['Spa-Male','Spa-Female']",
  "date_changed": "",
  "days_in_advance": 0,
  "docstatus": 0,
  "doctype": "SMS Notification",
  "document_type": "Client Appointment",
  "enabled": 1,
  "event": "Save",
  "interval": "",
  "is_standard": 0,
  "message": "<p><i>Dear {{doc.customer_name}},<br><br>\n\nYour spa booking has been modified as follows:<br><br>\n\nBooking details<br><br>\n\nName:{{doc.customer_name}}<br>\nTreatment Type: {{doc.service}}<br>\nBooking Date and Time: {{doc.scheduled_from_date}}</i></p>",
  "method": "",
  "modified": "2021-01-20 09:36:48.992879",
  "module": "",
  "name": "Your Spa Booking has been Rescheduled",
  "parent": "",
  "parentfield": "",
  "parenttype": "",
  "property_value": "",
  "recipients": [
   {
    "condition": "",
    "parent": "Your Spa Booking has been Rescheduled",
    "parentfield": "recipients",
    "parenttype": "SMS Notification",
    "receiver_by_document_field": "customer_phone_number",
    "receiver_by_role": ""
   }
  ],
  "send_system_notification": 0,
  "set_property_after_alert": "",
  "subject": "",
  "value_changed": "scheduled_from_date"
 }
]
    
    make_records(records)